#!/bin/sh

# ingredients: cool-and-crunchy

SHUFCOUNT=1

case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac

$SHUF <<EOSHUF
carrots
celery
cucumbers
green peppers
radishes
red peppers
salad
EOSHUF
