#!/bin/sh

# ingredients - green-and-leafy

SHUFCOUNT=1
case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac

$SHUF <<EOSHUF
chard
kale
parsley
spinach
EOSHUF
