#!/bin/sh
SHUFCOUNT=1
case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac

$SHUF <<EOSHUF
beans
black beans
cheese
chicken
chickpeas
eggs
fish
lentils
nuts
pizza
salmon
tofu
tuna
white beans
EOSHUF
