#!/bin/sh
SHUFCOUNT=1
case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac

$SHUF <<EOSHUF
bay leaf
chili
coconut
coriander
cumin
curry
dill
garlic
ginger
gochujang
miso
oregano
rosemary
thyme
turmeric
EOSHUF
