#!/bin/sh

SHUFCOUNT=1
case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac

$SHUF <<EOSHUF
bok choi
broccoli
broccoli rabe
cauliflower
green cabbage
napa cabbage
EOSHUF
