#!/bin/sh

SHUFCOUNT=1
case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n $SHUFCOUNT" ;;
        *)              SHUF="shuf -n $SHUFCOUNT" ;;
esac


$SHUF <<EOSHUF
bread
pasta
polenta
potatoes
rice
sweet potatoes
winter squash
EOSHUF
